/**
 * Prebuild script: generates src/lib/version.ts from package.json.
 * Run via `npm run prebuild`.
 */
const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));

const content = `/** Auto-generated by prebuild. Do not edit. */\nexport const SDK_VERSION = '${pkg.version}';\n`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'lib', 'version.ts'), content);

console.log(`[prebuild] Generated src/lib/version.ts → ${pkg.version}`);
